export default {
  GET_CASE_BY_ID_REQUEST: 'GET_CASE_BY_ID_REQUEST',
  GET_CASE_BY_ID_SUCCESS: 'GET_CASE_BY_ID_SUCCESS',
  GET_CASE_BY_ID_FAILURE: 'GET_CASE_BY_ID_FAILURE',
  GET_CASES_REQUEST: 'GET_CASES_REQUEST',
  GET_CASES_SUCCESS: 'GET_CASES_SUCCESS',
  GET_CASES_FAILURE: 'GET_CASES_FAILURE',
};
