language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test || travis_terminate 1
  - npm run lint-bail || travis_terminate 1
  - npm run flow || travis_terminate 1
  - npm run build
branches: 
  only:
    - master
